"""ampliar precision de condition a 4,2

Revision ID: 0dbfe62d5b5b
Revises: 1fc9f07dbc10
Create Date: 2026-08-10 17:20:52.661628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbfe62d5b5b'
down_revision = '1fc9f07dbc10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('frames', 'condition',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('frames', 'condition',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
