"""agregar condition a frames

Revision ID: 1fc9f07dbc10
Revises: 86578614693c
Create Date: 2026-08-10 16:31:58.998000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc9f07dbc10'
down_revision = '86578614693c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frames', sa.Column('condition', sa.Numeric(precision=3, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frames', 'condition')
    # ### end Alembic commands ###
